"""Updated users schema

Revision ID: 1341fbea9fc2
Revises: ea30fd5e20f4
Create Date: 2024-10-01 14:29:28.190739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1341fbea9fc2'
down_revision = 'ea30fd5e20f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('monthly_income',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('monthly_income',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
