"""Add an essential attribute to Category

Revision ID: 7cad0e05375a
Revises: 691567aa9200
Create Date: 2024-11-15 14:50:06.897351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cad0e05375a'
down_revision = '691567aa9200'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('essential', sa.Boolean(), nullable=True))
        batch_op.drop_column('is_predefined')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_predefined', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('essential')

    # ### end Alembic commands ###
