"""Updated users schema

Revision ID: b86db3bc4b03
Revises: 1341fbea9fc2
Create Date: 2024-10-01 15:15:15.032100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b86db3bc4b03'
down_revision = '1341fbea9fc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('monthly_income',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('monthly_income',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
