"""Make is_essential user specific and make category_id more safe in case of deletion

Revision ID: d489ab62f87c
Revises: 7cad0e05375a
Create Date: 2024-11-15 15:10:53.817764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd489ab62f87c'
down_revision = '7cad0e05375a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('essential')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('transactions_category_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('user_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_essential', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_categories', schema=None) as batch_op:
        batch_op.drop_column('is_essential')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('transactions_category_id_fkey', 'categories', ['category_id'], ['id'])
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('essential', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
