"""rename is_essential to essential

Revision ID: d5638c810787
Revises: d489ab62f87c
Create Date: 2024-11-16 15:54:41.470247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5638c810787'
down_revision = 'd489ab62f87c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('essential', sa.Boolean(), nullable=False))
        batch_op.drop_column('is_essential')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_essential', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('essential')

    # ### end Alembic commands ###
